language: php
php:
  - '7.4'
  - '7.3'
  - '7.2'

before_script:
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

deploy:
  provider: transifex
  controller: transifex.transifexapps.com
  api_token: $TRANSIFEX_API_TOKEN
  edge: true # opt in to dpl v2
