services:
  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\AlterRootComposerJsonMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\FriendlyConfigurationMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\SessionAttributeBagMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ComposerJsonMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\BundleClassMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\DependencyInjectionExtensionClassMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ContaoManagerPluginClassMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ContinuousIntegrationMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\MiscFilesMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\EasyCodingStandardMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ContaoBackendModuleMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ContaoFrontendModuleMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\ContaoContentElementMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\CustomRouteMaker:
    tags:
      - { name: kernel.event_subscriber }

  Markocupic\ContaoBundleCreatorBundle\Subscriber\Maker\AddStandardTagsMaker:
    tags:
      - { name: kernel.event_subscriber }