services:
    PhpCsFixer\Fixer\Comment\HeaderCommentFixer:
        header: "This file is part of Contao Bundle Creator Bundle.\n\n(c) Marko Cupic 2020 <m.cupic@gmx.ch>\n@license MIT\nFor the full copyright and license information, please view the LICENSE\nfile that was distributed with this source code.\n@link https://github.com/markocupic/contao-bundle-creator-bundle\n"
